defaults:
  - datasets@forget: Phone_Number_PII_forget
  - datasets@retain: Birth_City_PII_retain
  - datasets@full: Phone_Number_PII_full
  - datasets@forget_paraphrased: Phone_Number_PII_forget_paraphrased
  - datasets@retain_paraphrased: Birth_City_PII_retain_paraphrased
  - datasets@eval: Phone_Number_PII_forget

anchor: forget
