defaults:
  - datasets@forget: validation_Drivers_License_PII_forget
  - datasets@retain: validation_Email_Address_PII_retain
  - datasets@full: validation_Drivers_License_PII_full
  - datasets@forget_paraphrased: validation_Drivers_License_PII_forget_paraphrased
  - datasets@retain_paraphrased: validation_Email_Address_PII_retain_paraphrased
  - datasets@eval: validation_Drivers_License_PII_forget

anchor: forget
