Forget:
  data_path : ${paths.memorized_datasets_dir}
  name : 'Email_Address'
  split: 'forget'
  handler: QADataset
  args:
    hf_args:
      # question_key: "question"
      # answer_key: "answer"
      #max_length: 512
      path: ${unlearning_data.forget.Forget.data_path}
      name: ${unlearning_data.forget.Forget.name}
      split: ${unlearning_data.forget.Forget.split}

