# @package eval.panorama.metrics.exact_memorization_paraphrased
defaults:
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex

handler: exact_memorization
batch_size: ${eval.panorama.batch_size}
datasets: ${data.forget_paraphrased}
