# @package eval.panorama.metrics.extraction_strength_paraphrased
defaults:
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex

handler: extraction_strength
batch_size: ${eval.panorama.batch_size}
datasets: ${data.forget_paraphrased}
