# @package eval.panorama.metrics.extraction_strength
defaults:
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex

handler: extraction_strength
batch_size: ${eval.panorama.batch_size}
datasets: ${data.forget}
