# @package eval.panorama.metrics.forget_Q_A_Prob_paraphrased
defaults:
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  # ^ get default dataset and generation config information

handler: probability
batch_size: ${eval.panorama.batch_size}
datasets: ${data.forget_paraphrased}
