# @package eval.panorama.metrics.retain_exact_memorization
defaults:
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex

handler: exact_memorization
batch_size: ${eval.panorama.batch_size}
datasets: ${data.retain}
